package kz.lof.util;

public enum ResponseType {
	SAVE_FORM, 
	SAVE_FORM_OF_USER_PROFILE, 
	DO_HANDLER, 
	DELETE_ORGANIZATION, 
	UPLOAD_FILE,
	DELETE_DOCUMENT, 
	UNDELETE_DOCUMENT, 
	DELETE_USER, 
	RESET_RULES, 
	RESET_XSLT, 
	SAVE_FORM_OF_RULE,
	AUTHENTICATION
}
