package kz.lof.dataengine;

public enum DatabasePoolExceptionType {
	INTERNAL_DATABASE_ERROR,DATABASE_CONNECTION_REFUSED, DATABASE_AUTHETICATION_FAILED, DATABASE_SQL_ERROR, DATABASE_CONNECTION_ATTEMPT_FAILED 

}
